networks:
  cassandra-pace:
    driver: bridge

services:
  cassandra-db:
    image: "cassandra:5.0.4"
    container_name: "cassandra-db"
    ports:
      - "7000:7000"
      - "9042:9042"
    networks:
      - cassandra-pace
    deploy:
      resources:
        limits:
          memory: 8G
          cpus: '2'
        reservations:
          memory: 4G
    environment:
      - CASSANDRA_CLUSTER_NAME=pace-cluster
      - MAX_HEAP_SIZE=4G
      - HEAP_NEWSIZE=1G
    volumes:
      - ./infra/cassandra:/var/lib/cassandra:rw
    restart:
      on-failure:5
    healthcheck:
      test: [ "CMD-SHELL", "nodetool status" ]
      interval: 1m
      start_period: 3m
      timeout: 10s
      retries: 5
  keycloak:
    image: quay.io/keycloak/keycloak:26.3.1
    container_name: keycloak_web
    volumes:
      - ./infra/keycloak/:/opt/keycloak/data/import
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres-kc:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=password
      - KC_HOSTNAME=localhost
      - KC_HOSTNAME_PORT=8080
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_LOG_LEVEL=info
      - KC_METRICS_ENABLED=true
      - KC_HEALTH_ENABLED=true
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev --import-realm
#    healthcheck:
#      test: "curl -f http://localhost:8080/health/ready"
#      interval: 5s
#      timeout: 10s
#      retries: 10
    depends_on:
      postgres-kc:
        condition: service_healthy
    networks:
      - cassandra-pace
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 1G # 1 Gigabyte
        reservations:
          memory: 512M
  postgres-kc:
    image: postgres:15
    container_name: postgres-kc
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
    networks:
      - cassandra-pace
    deploy:
      resources:
        limits:
          memory: 1G # 1 Gigabyte
        reservations:
          memory: 512M

volumes:
  postgres_data:
